### ISSUE TITLE
[Bug]: `page::sinfo::AcceptError` is not exported

### ISSUE THREAD

**Issue by jarkkojs** [enarx/sgx#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

-

### Expected Behaviour

-

### Environment Information

-

**Comment by rvolosatovs** [comment]
Why is this a bug? Why does it *need* to be exported? What's the motivation for this change?

**Comment by jarkkojs** [comment]
> Why is this a bug? Why does it _need_ to be exported? What's the motivation for this change?

It's can be categorized as a bug because the functions that use the error code are part of exported API.
